spring:
  application:
    name: weather-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    city:
      path: /city/**
      serviceId: weather-city-eureka
    data:
      path: /data/**
      serviceId: weather-data-eureka
server:
  port: 8089